ileriWebVeriTabaniSoa/Controllers/LikesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ileriWebVeriTabaniSoa.Data;
using ileriWebVeriTabaniSoa.Models;
using Microsoft.AspNetCore.Authorization;

namespace ileriWebVeriTabaniSoa.Controllers
{
    [Authorize(Roles = "Admin,Writer")]
    public class LikesController : Controller
    {
        private readonly AppDbContext _context;

        public LikesController(AppDbContext context)
        {
            _context = context;
        }

        // GET: Likes
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Index()
        {
            var appDbContext = _context.Likes.Include(l => l.Post).Include(l => l.User);
            return View(await appDbContext.ToListAsync());
        }

        // GET: Likes/Details/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var like = await _context.Likes
                .Include(l => l.Post)
                .Include(l => l.User)
                .FirstOrDefaultAsync(m => m.LikeID == id);
            if (like == null)
            {
                return NotFound();
            }

            return View(like);
        }

        // GET: Likes/Create
        [Authorize(Roles = "Admin,Writer")]
        public IActionResult Create()
        {
            ViewData["PostID"] = new SelectList(_context.Posts, "Id", "Id");
            ViewData["UserID"] = new SelectList(_context.Users, "UserId", "Email");
            return View();
        }

        // POST: Likes/Create
        // POST: Likes/Create
    [Authorize(Roles = "Admin,Writer")]
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create([Bind("LikeID,PostID,UserID,LikedDate")] Like like)
    {
    // Kullanıcıyı al
    var currentUser = HttpContext.User;
    var name = currentUser.Identity.Name;
    var user = _context.Users.Where(x => x.Username == name).FirstOrDefault();

    // Kullanıcının bu gönderiyi daha önce beğenip beğenmediğini kontrol et
    var existingLike = _context.Likes
        .FirstOrDefault(l => l.PostID == like.PostID && l.UserID == user.UserId);

    if (existingLike != null)
    {
        // Kullanıcı zaten beğenmiş, işlemi iptal et
        return RedirectToAction("Details", "Posts", new { id = like.PostID });
    }

    // Kullanıcı daha önce beğenmemişse, beğeni ekle
    like.UserID = user.UserId;
    _context.Add(like);
    await _context.SaveChangesAsync();

    // Beğeni ekledikten sonra Post detay sayfasına yönlendir
    return RedirectToAction("Details", "Posts", new { id = like.PostID });
}
        // GET: Likes/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var like = await _context.Likes.FindAsync(id);
            if (like == null)
            {
                return NotFound();
            }
            ViewData["PostID"] = new SelectList(_context.Posts, "Id", "Id", like.PostID);
            ViewData["UserID"] = new SelectList(_context.Users, "UserId", "Email", like.UserID);
            return View(like);
        }

        // POST: Likes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("LikeID,PostID,UserID,LikedDate")] Like like)
        {
            if (id != like.LikeID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(like);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LikeExists(like.LikeID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["PostID"] = new SelectList(_context.Posts, "Id", "Id", like.PostID);
            ViewData["UserID"] = new SelectList(_context.Users, "UserId", "Email", like.UserID);
            return View(like);
        }

        // GET: Likes/Delete/5
        [Authorize(Roles = "Admin,Writer")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var like = await _context.Likes
                .Include(l => l.Post)
                .Include(l => l.User)
                .FirstOrDefaultAsync(m => m.LikeID == id);
            if (like == null)
            {
                return NotFound();
            }

            return View(like);
        }

        // POST: Likes/Delete/5
        [Authorize(Roles = "Admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var like = await _context.Likes.FindAsync(id);
            if (like != null)
            {
                _context.Likes.Remove(like);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        [Authorize(Roles = "Admin,Writer")]
        [HttpPost]
        public IActionResult LikeDelete(int PostID)
        {
            var currentUser = HttpContext.User;  // Kullanıcı bilgilerini al
            var name = currentUser.Identity.Name;  // Kullanıcının adını al
            var user = _context.Users.Where(x => x.Username == name).FirstOrDefault();  // Kullanıcıyı veritabanında ara

            if (user != null)
            {
                var like = _context.Likes
                                   .FirstOrDefault(l => l.PostID == PostID && l.UserID == user.UserId);  // Kullanıcıya ait beğeniyi bul

                if (like != null)
                {
                    _context.Likes.Remove(like);  // Beğeniyi sil
                    _context.SaveChanges();  // Değişiklikleri kaydet
                }
            }

            return RedirectToAction("Details", "Posts", new { id = PostID });  // Kullanıcıyı ilgili sayfaya yönlendir
        }


        [Authorize(Roles = "Admin,Writer")]
        private bool LikeExists(int id)
        {
            return _context.Likes.Any(e => e.LikeID == id);
        }
    }
}

ileriWebVeriTabaniSoa/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ileriWebVeriTabaniSoa.Data;
using ileriWebVeriTabaniSoa.Models;
using ileriWebVeriTabaniSoa.Helpers; // Helpers klasöründeki sınıfı dahil ediyoruz
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
namespace ileriWebVeriTabaniSoa.Controllers
{
    [Authorize(Roles = "Admin")]
    public class UsersController : Controller
    {
        private readonly AppDbContext _context;

        public UsersController(AppDbContext context)
        {
            _context = context;
        }

        // GET: Users
        public async Task<IActionResult> Index()
        {
            return View(await _context.Users.ToListAsync());
        }

        // GET: Users/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.Users
                .FirstOrDefaultAsync(m => m.UserId == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // GET: Users/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Users/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("UserId,Username,Email,Password,Role")] User user)
        {
            if (_context.Users.Any(u => u.Email == user.Email))
            {
                ModelState.AddModelError("Email", "Bu e-posta adresi zaten kullanılıyor.");
                return View(user);
            }

            if (ModelState.IsValid)
            {
                // Şifreyi hashle
                var passwordHasher = new PasswordHasher<User>();
                user.Password = passwordHasher.HashPassword(user, user.Password);

                // Kullanıcı oluşturulma tarihini UTC olarak ata
                user.CreatedDate = DateTime.UtcNow;

                _context.Add(user);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            return View(user);
        }

        // GET: Users/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            Console.WriteLine("asdasd111");
            if (id == null)
            {
                Console.WriteLine("idnull");
                return NotFound();
            }

            var user = await _context.Users.FindAsync(id);
            if (user == null)
            {
                Console.WriteLine("usernull");
                return NotFound();
            }

            // Şifreyi ve CreatedDate'yi formda göstermiyoruz
            return View(user);
        }


        // POST: Users/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("UserId,Username,Email,Role")] UserEditDTO user)
        {
            Console.WriteLine("edite girdi.");
            if (id != user.UserId)
            {
                Console.WriteLine("userid Null");
                return NotFound();
            }

            Console.WriteLine("xxxxxx");
            Console.WriteLine(ModelState.IsValid);
            if (ModelState.IsValid)
            {
                Console.WriteLine("modelstate valide girdi.");
                try
                {
                    // Veri tabanından mevcut kullanıcıyı getir
                    var existingUser = await _context.Users.FirstOrDefaultAsync(u => u.UserId == id);
                    if (existingUser == null)
                    {
                        Console.WriteLine("kullaniciyi getir");
                        return NotFound();
                    }

                    // Kullanıcının şifresini değiştirme
                    existingUser.Password = existingUser.Password;  // Eski şifreyi koruyun

                    // Kullanıcı adı ve diğer bilgileri güncelle
                    existingUser.Username = user.Username;
                    existingUser.Email = user.Email;
                    existingUser.Role = user.Role;

                    // CreatedDate'yi değiştirmiyoruz
                    existingUser.CreatedDate = existingUser.CreatedDate;

                    // Entity Framework'e değişikliğin olduğunu bildir
                    _context.Entry(existingUser).State = EntityState.Modified;

                    // Değişiklikleri kaydet
                    await _context.SaveChangesAsync();

                    Console.WriteLine("Kullanıcı başarıyla güncellendi.");
                    return RedirectToAction(nameof(Index));
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UserExists(user.UserId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
            }

            // Eğer ModelState geçerli değilse, hatayı formda göster
            Console.WriteLine("ModelState geçerli değil!");
            foreach (var error in ModelState.Values.SelectMany(v => v.Errors))
            {
                Console.WriteLine($"Hata: {error.ErrorMessage}");
            }

            return View(user);
        }











        // GET: Users/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.Users
                .FirstOrDefaultAsync(m => m.UserId == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var user = await _context.Users.FindAsync(id);
            if (user != null)
            {
                _context.Users.Remove(user);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UserExists(int id)
        {
            return _context.Users.Any(e => e.UserId == id);
        }
    }
}

ileriWebVeriTabaniSoa/Views/Shared/AccessDenied.cshtml
@{
    Layout = null;
}

<div class="access-denied-container">
    <h1>Yetki Yok</h1>
    <p>Bu sayfaya erişim yetkiniz bulunmamaktadır.</p>
    <p>Eğer bunun bir hata olduğunu düşünüyorsanız, lütfen yöneticinizle iletişime geçin.</p>

    <!-- Butonu yazıların altına koyduk -->
    <a href="/" class="home-button">
        <i class="fas fa-home"></i> Anasayfaya Git
    </a>
</div>

<style>
    .access-denied-container {
        text-align: center;
        padding: 20px;
        margin-top: 100px;
    }

    .home-button {
        display: inline-block; /* Butonu yazıların altına yerleştirmek için */
        margin-top: 20px; /* Yazılardan biraz boşluk bırakmak için */
        background-color: #007bff;
        color: #fff;
        text-decoration: none;
        padding: 10px 15px;
        border-radius: 5px;
        font-size: 1rem;
        box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
    }

        .home-button:hover {
            background-color: #0056b3;
        }
</style>

ileriWebVeriTabaniSoa/Views/Shared/PartialView.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

ileriWebVeriTabaniSoa/Views/Shared/_Layout.cshtml
<!doctype html>
<html lang="en">
<head>
    <title>MyBlog</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css?family=Josefin+Sans:300, 400,700|Inconsolata:400,700" rel="stylesheet">
    <link rel="stylesheet" href="~/Assets/css/bootstrap.css">
    <link rel="stylesheet" href="~/Assets/css/animate.css">
    <link rel="stylesheet" href="~/Assets/css/owl.carousel.min.css">
    <link rel="stylesheet" href="~/Assets/fonts/ionicons/css/ionicons.min.css">
    <link rel="stylesheet" href="~/Assets/fonts/fontawesome/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/Assets/fonts/flaticon/font/flaticon.css">
    <!-- Theme Style -->
    <link rel="stylesheet" href="~/Assets/css/style.css">
</head>
<body>

    <div class="wrap">
        <header role="banner">
            <div class="top-bar">
                <div class="container">
                    <div class="row">
                        <div class="col-9 social">
                            <a href="#"><span class="fa fa-twitter"></span></a>
                            <a href="#"><span class="fa fa-facebook"></span></a>
                            <a href="#"><span class="fa fa-instagram"></span></a>
                            <a href="#"><span class="fa fa-youtube-play"></span></a>

                        </div>

                         @* <div class="col-3 search-top"> *@
                         @*    <form asp-action="Search" asp-controller="Home" method="get"> *@
                         @*        <span class="icon fa fa-search"></span> *@
                         @*        <input type="text" name="query" placeholder="Search..." /> *@
                         @*    </form> *@
                         @* </div>  *@
                         <form asp-action="Search" asp-controller="Home" method="get"> 
                             <input type="text" name="query" placeholder="Search..." /> 
                             <button type="submit">Search</button> 
                         </form> 
                    </div>
                </div>
            </div>

            <div class="container logo-wrap">
                <div class="row pt-5">
                    <div class="col-12 text-center">
                        <a class="absolute-toggle d-block d-md-none" data-toggle="collapse" href="#navbarMenu" role="button" aria-expanded="false" aria-controls="navbarMenu"><span class="burger-lines"></span></a>
                        <h1 class="site-logo"><a href="/#">Myblog</a></h1>
                    </div>
                </div>
            </div>

            <nav class="navbar navbar-expand-md navbar-light bg-light">
                <div class="container">
                    <div class="collapse navbar-collapse" id="navbarMenu">
                        <ul class="navbar-nav mx-auto">
                            <li class="nav-item">
                               
                                <a class="nav-link" href="/#">Main Page</a>
                            </li>
                            

                            @await Component.InvokeAsync("CategoryList")

                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Home" asp-action="About">About</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Home" asp-action="Contact">Contact</a>
                            </li>
                            @if (User.Identity.IsAuthenticated)
                            {
                                //PartialView Kullanim
                                @await Html.PartialAsync("~/Views/Partials/WelcomePartial.cshtml")
                                <li class="nav-item">
                                    <a class="nav-link" asp-controller="Account" asp-action="Logout">Logout</a>
                                </li>
                            }
                            else
                            {
                                <li class="nav-item">
                                    <a class="nav-link" asp-controller="Account" asp-action="Login">Login</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" asp-controller="Account" asp-action="Register">Register</a>
                                </li>
                            }
                            @if (User.IsInRole("Admin"))
                            {
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="#" id="adminDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                        Admin Procceses
                                    </a>
                                    <ul class="dropdown-menu" aria-labelledby="adminDropdown">

                                        <li><a class="dropdown-item" asp-controller="Users" asp-action="Index">User  Management</a></li>
                                        <li><a class="dropdown-item" asp-controller="Posts" asp-action="Index">Post Management</a></li>
                                        <li><a class="dropdown-item" asp-controller="Categories" asp-action="Index">Category  Management</a></li>
                                        <li><a class="dropdown-item" asp-controller="Comments" asp-action="Index">Comments Management</a></li>
                                        <li><a class="dropdown-item" asp-controller="Likes" asp-action="Index">Likes Management</a></li>
                                    </ul>
                                </li>
                            }
                        </ul>
                    </div>
                </div>
            </nav>

        </header>

        <!-- Content Section -->
        @RenderBody()

        <footer class="site-footer">
            <div class="container">
                <div class="row mb-5">
                    <div class="col-md-4">
                        <h3>About Us</h3>
                        <p class="mb-4">
                            <img src="~/Assets/images/img_1.jpg" alt="Image placeholder" class="img-fluid">
                        </p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsa harum inventore reiciendis. <a href="#">Read More</a></p>
                    </div>
                    <div class="col-md-6 ml-auto">
                        <div class="row">
                            <div class="col-md-4">
                                <div class="mb-5">
                                    <h3>Social</h3>
                                    <ul class="list-unstyled footer-social">
                                        <li><a href="#"><span class="fa fa-twitter"></span> Twitter</a></li>
                                        <li><a href="#"><span class="fa fa-facebook"></span> Facebook</a></li>
                                        <li><a href="#"><span class="fa fa-instagram"></span> Instagram</a></li>
                                        <li><a href="#"><span class="fa fa-youtube-play"></span> Youtube</a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12 text-center">
                        <p class="small">
                            Copyright &copy; <script data-cfasync="false" src="/cdn-cgi/scripts/5c5dd728/cloudflare-static/email-decode.min.js"></script><script>document.write(new Date().getFullYear());</script> All Rights Reserved | This template is made with <i class="fa fa-heart text-danger" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
                        </p>
                    </div>
                </div>
            </div>
        </footer>
    </div>

    <script src="~/Assets/js/jquery-3.2.1.min.js"></script>
    <script src="~/Assets/js/jquery-migrate-3.0.0.js"></script>
    <script src="~/Assets/js/popper.min.js"></script>
    <script src="~/Assets/js/bootstrap.min.js"></script>
    <script src="~/Assets/js/owl.carousel.min.js"></script>
    <script src="~/Assets/js/jquery.waypoints.min.js"></script>
    <script src="~/Assets/js/jquery.stellar.min.js"></script>
    <script src="~/Assets/js/main.js"></script>

    

    @RenderSection("Scripts", required: false)
</body>
</html>