ileriWebVeriTabaniSoa/Models/Category.cs
using System.ComponentModel.DataAnnotations;

namespace ileriWebVeriTabaniSoa.Models
{
    public class Category
    {
        public int CategoryID { get; set; } // Primary Key
        [Required]
        [StringLength(100)]
        public string Name { get; set; }


        // İlişkiler
        public ICollection<Post>? Posts { get; set; } // Kategoriye ait gönderiler
    }
}

ileriWebVeriTabaniSoa/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ileriWebVeriTabaniSoa.Data;
using ileriWebVeriTabaniSoa.Models;
using Microsoft.AspNetCore.Authorization;

namespace ileriWebVeriTabaniSoa.Controllers
{
    [Authorize(Roles = "Admin")]
    public class CategoriesController : Controller
    {
        private readonly AppDbContext _context;

        public CategoriesController(AppDbContext context)
        {
            _context = context;
        }

        // GET: Categories
        public async Task<IActionResult> Index()
        {
            return View(await _context.Categories.ToListAsync());
        }

        // GET: Categories/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Categories
                .FirstOrDefaultAsync(m => m.CategoryID == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // GET: Categories/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Categories/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CategoryID,Name")] Category category)
        {
            if (!ModelState.IsValid)
            {
                foreach (var error in ModelState.Values.SelectMany(v => v.Errors))
                {
                    Console.WriteLine(error.ErrorMessage);
                }
                return View(category);
            }
            if (ModelState.IsValid)
            {

                _context.Add(category);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(category);

        }

        // GET: Categories/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Categories.FindAsync(id);
            if (category == null)
            {
                return NotFound();
            }
            return View(category);
        }

        // POST: Categories/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("CategoryID,Name")] Category category)
        {
            if (id != category.CategoryID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(category);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CategoryExists(category.CategoryID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }

        // GET: Categories/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Categories
                .FirstOrDefaultAsync(m => m.CategoryID == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // POST: Categories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var category = await _context.Categories
                .Include(c => c.Posts) // İlgili postları da dahil et
                .FirstOrDefaultAsync(m => m.CategoryID == id);

            if (category != null)
            {
                // Kategoriye ait yazıları sil
                _context.Posts.RemoveRange(category.Posts);

                // Kategoriyi sil
                _context.Categories.Remove(category);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        // Kategorileri herkes görebilsin
        [AllowAnonymous] // Bu, kategorilere genel erişim sağlar
        public async Task<IActionResult> GetCategory()
        {
            var categories = await _context.Categories.ToListAsync();
            if (categories == null || categories.Count == 0)
            {
                Console.WriteLine("No categories found in the database.");
            }
            else
            {
                Console.WriteLine($"Found {categories.Count} categories.");
            }

            ViewData["Categories"] = categories;

            return View();
        }
        [AllowAnonymous]
        public async Task<IActionResult> CategorySelect(int id)
        {
            // Veritabanından seçilen kategoriye ait postları almak
            var posts = await _context.Posts
                                      .Where(p => p.CategoryID == id)
                                      .ToListAsync();

            // Kategorilere göre filtrelenmiş postları view'e göndermek
            return View(posts);
        }
        private bool CategoryExists(int id)
        {
            return _context.Categories.Any(e => e.CategoryID == id);
        }
    }
}

ileriWebVeriTabaniSoa/Controllers/PostsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ileriWebVeriTabaniSoa.Data;
using ileriWebVeriTabaniSoa.Models;
using Microsoft.AspNetCore.Authorization;
using System.Security.Claims;

namespace ileriWebVeriTabaniSoa.Controllers
{
    [Authorize(Roles = "Admin,Writer")]
    public class PostsController : Controller
    {
        private readonly AppDbContext _context;

        public PostsController(AppDbContext context)
        {
            _context = context;
        }
        [Route("[controller]")]
        public class PostController : Controller
        {

            [HttpGet]
            public IActionResult Index()
            {
                return View();
            }
        }
        // GET: Posts
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Index()
        {
            var appDbContext = _context.Posts.Include(p => p.User);
            return View(await appDbContext.ToListAsync());
        }

        // GET: Posts/Details/5
        [AllowAnonymous]
        public IActionResult Details(int id)
        {
            var post = _context.Posts.Include(p => p.Category).Include(p => p.Likes).Include(p => p.Comments).ThenInclude(p => p.User)
                                     .FirstOrDefault(p => p.Id == id);
            if (post == null)
            {
                return NotFound();
            }
            return View(post);
        }

        // GET: Posts/Create
        [Authorize(Roles = "Admin,Writer")]
        public async Task<IActionResult> Create()
        {

            Console.WriteLine("buney");

            ViewData["UserId"] = new SelectList(_context.Users, "UserId", "Email");
            var categories = await _context.Categories.ToListAsync();  // Kategorileri veritabanından alıyoruz
            ViewBag.categories = new SelectList(categories, "CategoryID", "Name");  // Kategorileri ViewBag'e atıyoruz
            return View();
        }

        // POST: Posts/Create
        [Authorize(Roles = "Admin,Writer")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,Content,UserId,CategoryID")] Post post)
        {

            // Kullanıcının Email veya başka bir kimlik bilgisi üzerinden ID'sini alın
            var currentUser = HttpContext.User;

            var name = currentUser.Identity.Name;


            var user=_context.Users.Where(x => x.Username == name).FirstOrDefault();



             // Kategori kontrolü
             var isValidCategory = _context.Categories.Any(c => c.CategoryID == post.CategoryID);
            if (!isValidCategory)
            {
                Console.WriteLine("Geçersiz kategori seçimi.");
                ModelState.AddModelError("CategoryID", "Please select a category.");
                return View(post);
            }

            if (ModelState.IsValid)
            {
                // Kullanıcıyı ve kategoriyi atıyoruz
                // Alınan kullanıcı ID'sini atıyoruz
                post.UserId = user.UserId;

                // Postu veritabanına ekliyoruz
                _context.Add(post);
                await _context.SaveChangesAsync();

                return RedirectToAction("Index", "Home"); // Ana sayfaya yönlendiriyoruz
            }
            if (!ModelState.IsValid)
            {
                foreach (var modelState in ModelState.Values)
                {
                    foreach (var error in modelState.Errors)
                    {
                        Console.WriteLine("xxxxxxxx");
                        Console.WriteLine(error.ErrorMessage);
                    }
                }
            }

            // Hata durumunda kategorileri geri döndürüyoruz
            //ViewData["UserId"] = userId;
            return View(post);
        }


        // GET: Posts/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var post = await _context.Posts.FindAsync(id);
            if (post == null)
            {
                return NotFound();
            }
            ViewData["UserId"] = new SelectList(_context.Users, "UserId", "Email", post.UserId);
            return View(post);
        }

        // POST: Posts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Content,UserId,Category")] Post post)
        {
            if (id != post.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(post);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PostExists(post.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["UserId"] = new SelectList(_context.Users, "UserId", "Email", post.UserId);
            return View(post);
        }
        [Authorize(Roles = "Admin")]
        // GET: Posts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();

            }
            
            var post = await _context.Posts
                .Include(p => p.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (post == null)
            {
                return NotFound();
            }

            return View(post);
        }
        [Authorize(Roles = "Admin")]
        // POST: Posts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var post = await _context.Posts.FindAsync(id);
            if (post != null)
            {
                _context.Posts.Remove(post);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
       

        private bool PostExists(int id)
        {
            return _context.Posts.Any(e => e.Id == id);
        }
    }
}

ileriWebVeriTabaniSoa/Views/Categories/CategorySelect.cshtml
@model List<ileriWebVeriTabaniSoa.Models.Post>

<div class="container mt-4">
    <h2>Posts in Selected Category</h2>
    @if (Model.Any())
    {
        <ul class="list-group">
            @foreach (var post in Model)
            {
                <li class="list-group-item">
                    <h5>
                        <!-- Gönderi başlığını tıklanabilir bir bağlantı haline getiriyoruz -->
                        <a href="@Url.Action("Details", "Posts", new { id = post.Id })">@post.Title</a>
                    </h5>
                    <p>@post.Content</p>
                </li>
            }
        </ul>
    }
    else
    {
        <p>No posts found for this category.</p>
    }
</div>

ileriWebVeriTabaniSoa/Views/Categories/Create.cshtml
@model ileriWebVeriTabaniSoa.Models.Category

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Category</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

ileriWebVeriTabaniSoa/Views/Categories/Delete.cshtml
@model ileriWebVeriTabaniSoa.Models.Category

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Category</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="CategoryID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

ileriWebVeriTabaniSoa/Views/Categories/Details.cshtml
@model ileriWebVeriTabaniSoa.Models.Category

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Category</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.CategoryID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

ileriWebVeriTabaniSoa/Views/Categories/Edit.cshtml
@model ileriWebVeriTabaniSoa.Models.Category

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Category</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="CategoryID" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ileriWebVeriTabaniSoa/Views/Categories/Index.cshtml
@model IEnumerable<ileriWebVeriTabaniSoa.Models.Category>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.CategoryID">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.CategoryID">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.CategoryID">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>